# Note that in reality essentially all of these functions would require oath security, but it makes them hard to test
# through the swagger web ui (as you have to send the authorization header, I don't yet know how to do from there...?)
# so only /account get has oath implemented.
openapi: 3.0.0
info:
  description: Minimal Client Example
  version: "0.3.0-oas3"
  title: Minimal Client Example (OAS 3.0)
servers:
  - url: 'http://localhost:8080/'
paths:
  '/':
    get:
      operationId: microsetta_private_api.example.client_impl.rootpath
      responses:
        '302':
          description: Redirect to home page
  '/home':
    get:
      operationId: microsetta_private_api.example.client_impl.home
      responses:
        '200':
          description: Home Page
          content:
            text/html:
              schema:
                type: string
  '/authrocket_callback':
    get:
      operationId: microsetta_private_api.example.client_impl.authrocket_callback
      parameters:
        - in: query
          name: token
          schema:
            type: string
      responses:
        '302':
          description: Returning home
  '/logout':
    get:
      operationId: microsetta_private_api.example.client_impl.logout
      responses:
        '302':
          description: Returning home

#  '/create_account_wizard':
#    get:
#      operationId: microsetta_private_api.example.client_impl.create_account
#      responses:
#        '200'
#
